# Generated by Django 5.1 on 2024-09-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favoriterecipes_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
