# Generated by Django 5.1 on 2024-08-11 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы', regex='^[\\w.@+-]+\\Z')], verbose_name='Уникальный юзернейм'),
        ),
    ]
